kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgresbackup
  namespace: sgi-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: azurefile-csi
